### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Handsomekaizer** [stuartinnes/randstr#3]
hello sir 
Sorry to bother I was going through GitHub to see if I could find help then I stumbled on your repo, The problem I have is with this Go code

package main

// Project rand-string
// file: main.go
// Author: handsomekaizer <ubongetimanthony@gmail.com>
// Description: random string generator

import (
	"crypto/rand"
	"fmt"
	"math/big"
)

const RANDOM_STR_LEN = 10

func shuffleDict(dict string) []rune {
	shuffledDict := []rune(dict)
	for i := 0; i < len(dict); i++ {
		r, _ := rand.Int(rand.Reader, big.NewInt(int64(len(dict))))
		randn := r.Int64()
		char := shuffledDict[i]
		shuffledDict[i] = shuffledDict[randn]
		shuffledDict[randn] = char
	}
	return shuffledDict
}

func main() {
	fmt.Println("Here:")
	var dictionary string = "abcdefghiklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	for k := 0; k < 100; k++ {
		shuffledDict := shuffleDict(dictionary)
		for j := 0; j < RANDOM_STR_LEN; j++ {
			i, _ := rand.Int(rand.Reader, big.NewInt(int64(len(dictionary))))
			fmt.Printf("%c", shuffledDict[i.Int64()])
		}
		fmt.Printf("\n")
	}
}

The Go code is ok, it generates 10 alphanumeric characters. but I wanted you to help me add a function where it generates the 10 alphanumeric characters and  replaces **********
in this characters below

5m**********kbgTRZhiS5sjGMpmcRZdPAhmWLRfpmutGmPHtjklob

 with the 10 alphanumeric characters it generates.

thanks

**Comment by stuartinnes** [comment]
Hi, the random string generator in main.go is very efficient and I would recommend using that instead of what you have here - feel free to copy it. 

Your shuffling quite a lot of value many times when you really only need a small string and a single shuffle should be enough.

I suggest you create a function such as 

```
RandReplaceInString(from, to int, orginalValue){
  //validate from and to are valid 
 
  //generate a random string getRandStr(round(totalLen/2), round(totalLen/2), 0, 0) 

 //string replace   
  
}
```

Not at a computer right now but hopefully this helps.
